### ISSUE TITLE
TLS handshake error using DTLS on updatehub cloud

### ISSUE THREAD

**Issue by youssefchei-xite** [UpdateHub/zephyr#3]
**Describe the bug**
I'm testing the **updatehub** using nrf5340dk and quectel BG95 as modem.
I used the zephyr/samples/subsys/mgmt/updatehub sample and I used the **updatehub cloud** (free version for now) for update 
1- I build and flash version 1.0.0
2-Create and push the update package 2.0.0 to updatehub cloud using https://docs.updatehub.io/zephyr-project/zephyr-project-guide/ , steps: 8-9 then create rollout using step 11
3- start the FOTA using **updatehub run** command
4- the nrf5340dk connect to **updatehub cloud**, download the binary and update it after reboot and the firmware 2.0.0 is running.

Then I tested the updatehub with DTLS by including overlay-dtls.conf using the default certificates.
But I always got
[00:02:15.450,164] <err> net_sock_tls: TLS handshake error: -6800
[00:02:15.459,075] <err> updatehub: Could not send request
[00:02:15.473,327] <err> main: Invalid response

Is there a certificate that must upload to updatehub cloud?
Is there any config missing to make the updatehub example connect to updatehub cloud using DTLS ?

**To Reproduce**

build the updatehub sample
west build --board=nrf5340dk_nrf5340_cpuapp -d build zephyr/samples/subsys/mgmt/updatehub --\
-DOVERLAY_CONFIG="overlay-modem.conf;overlay-dtls.conf"

flash the binaries
west flash -d build

**Logs and console output**
```
[00:00:11.155,303] <inf> main: Network connected
[00:00:12.205,657] <inf> main: Starting UpdateHub manual mode
uart:~$
[00:02:15.450,164] <err> net_sock_tls: TLS handshake error: -6800
[00:02:15.459,075] <err> updatehub: Could not send request ret:-1 errno:0x71  113
[00:02:15.473,327] <err> main: Invalid response

```
**Environment (please complete the following information):**

- OS: MacOS
- Toolchain :nrf Connect SDK v1.7.0
- Zephyr version used:v2.6.99-ncs1

**Comment by nandojve** [comment]
Hi @youssefchei-xite ,

We are already looking at https://github.com/zephyrproject-rtos/zephyr/issues/42134.
There is no need to duplicate issue here.

We'll follow up there.
